### ISSUE TITLE
[Not an issue] Thank you for making this.

### ISSUE THREAD

**Issue by pizzadude** [winneon/watch-with-mpv#1]
Thank you for making this!

It works really good in Ubuntu MATE 17.10 which is the distro I am using.

It even works when Vivaldi (the chromium based browser I'm using) is sandboxed in firejail!

No mucking around with firejail profiles either.

Thank you Thank you Thank you

**Comment by winneon** [comment]
Thank you for the feedback! I really appreciate it! :)
