### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Mioni** [winneon/watch-with-mpv#5]
Hi, every time I click to watch this error appears.
![capture](https://user-images.githubusercontent.com/6830783/32463220-4ac3c250-c323-11e7-877c-e3a1539b46ba.PNG)

W10 RS3
Vivaldi 1.12

**Comment by winneon** [comment]
Vivaldi is not supported as of right now. The native host is not registered with other browsers and the extension will likely fail if you're using a different browser other than Chrome. I'll add Vivaldi to the TODO list, I apologize for the inconvenience.
