### ISSUE TITLE
Can't get it to work on Chrome

### ISSUE THREAD

**Issue by lucario386** [winneon/watch-with-mpv#6]
Not sure what is wrong, could you help me on this? I followed the instructions carefully, installed the extension first before using the installer, and have the latest youtube-dl and mpv.

![2017-12-11_13-51-58](https://user-images.githubusercontent.com/12094600/33817448-a5968c0e-de7a-11e7-8de3-bb4800ed5418.png)

Tried YouTube and Twitch and got this error, really want to use your extension :(

**Comment by winneon** [comment]
I have this issue too, I've been looking into it lately. I'll let you know when I find the problem.

**Comment by winneon** [comment]
I don't seem to be having this issue ever since youtube-dl updated on the 14th. Can you confirm it's working fine for you as well?

**Comment by winneon** [comment]
It's been almost a month since I asked and you have yet to respond, so I'm going to mark this as invalid unless proven otherwise.
